name: VineCoins
version: '1.0-SNAPSHOT'
main: me.ipapervn.vinecoins.VineCoins
api-version: '1.21'
load: STARTUP
authors: [ ipaperVN, iStudioVN ]
description: Plugin Currencies for VineSkyblock

commands:
  vinecoins:
    description: main command
    aliases: [vcoins, vc]